version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*github-script*"

  - package-ecosystem: docker
    directory: "./dockerfiles"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "./dockerfiles/maven"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "./dockerfiles/multi"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "./dockerfiles/node"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "./dockerfiles/python"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "./dockerfiles/sidekick"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10    
  - package-ecosystem: docker
    directory: "./dockerfiles/agent-discovery"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
