repo:
  - changed-files:
    - any-glob-to-any-file: '**'

controller:
  - changed-files:
      - any-glob-to-any-file: 'dockerfiles/Dockerfile/**'

python_project:
  - changed-files:
      - any-glob-to-any-file: 'dockerfiles/python/**'

test:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/coverage.yml'

docker:
  - changed-files:
      - any-glob-to-any-file: '/**/Dockerfile'

docker_compose:
  - changed-files:
      - any-glob-to-any-file: '/**/*docker-compose*.yml'


github_actions:
  - changed-files:
      - any-glob-to-any-file: '/.github/workflows/*'