services:
  sidekick_service:
    build: dockerfiles/sidekick/.
    stdin_open: true
    tty: true
    entrypoint: sh -c "/usr/local/bin/keygen.sh /ssh-dir" 
      - agent-ssh-dir:/ssh-dir 
    healthcheck:
      test: ["CMD-SHELL", "[ -f /ssh-dir/conductor_ok ] || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
  discovery_and_jcasc_modifier:
    build: dockerfiles/agent-discovery/.
    stdin_open: true
    tty: true
    entrypoint: sh -c "/usr/local/bin/find-name.sh"
    profiles:
      - python
      - default
    depends_on:
      sidekick_service:
        condition: service_completed_successfully 
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/find-name.sh || exit 0"]
      interval: 5s
      timeout: 10s
      retries: 50
    volumes:
      - jenkins_home:/var/jenkins_home 
      - agent-ssh-dir:/ssh-dir 
      - ./secrets/:/secrets/ 
  jenkins_controller:
    build: dockerfiles/.
    restart: on-failure
    environment:
      - CASC_RELOAD_TOKEN=thisisnotsecure
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home 
      - agent-ssh-dir:/ssh-dir 
      - ./secrets/jcasc_token:/run/secrets/CASC_RELOAD_TOKEN:ro
    depends_on:
      sidekick_service:
        condition: service_completed_successfully 
    healthcheck:
      test: ["CMD-SHELL", "[ -f /ssh-dir/conductor_ok ] || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
  default_agent:
    image: jenkins/ssh-agent:6.9.0
    container_name: desktop-jenkins_agent-1
    profiles:
      - default
    depends_on:
      sidekick_service:
        condition: service_completed_successfully 
      jenkins_controller:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "[ -f /home/jenkins/.ssh/authorized_keys ] || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - agent-ssh-dir:/home/jenkins/.ssh:ro 
  python:
    build: dockerfiles/python/.
    container_name: desktop-jenkins_agent-1-python
    profiles:
      - python
    depends_on:
      sidekick_service:
        condition: service_completed_successfully
      jenkins_controller:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "[ -f /home/jenkins/.ssh/authorized_keys ] || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - agent-ssh-dir:/home/jenkins/.ssh:ro 
  volumes:
  jenkins_home: null
  agent-ssh-dir:
    name: agent-ssh-dir 