
services:
  app:
    container_name: to-do-app
    build:
      context: .
    stdin_open: true
    tty: true
    init: true
    environment:
    depends_on:
    volumes:
      - .:/var/www/app
    ports:
      - "${APP_PORT:-8000}:8000"

  jenkins:
    container_name: jenkins
    build: 
      context:
    stdin_open: true
    tty: true
    init: true
    environment: 
    depends_on:
      - serviceName
    volumes:
    ports:

volumes:
  
