
services:
  sidekick_service:
    image: ${IMAGE_PREFIX}/${GHCR_USERNAME}/quickstart-tutorials/jenkinsci-tutorials:sidekick_${BRANCH_SUFFIX}
    stdin_open: true
    tty: true
    entrypoint: sh -c "/usr/local/bin/keygen.sh /ssh-dir" 
    volumes:
      - agent-ssh-dir:/ssh-dir 
    healthcheck:
      test: ["CMD-SHELL", "[ -f /ssh-dir/conductor_ok ] || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5

  discovery_and_jcasc_modifier:
    image: ${IMAGE_PREFIX}/${GHCR_USERNAME}/quickstart-tutorials/jenkinsci-tutorials:agent_discovery_${BRANCH_SUFFIX}
    stdin_open: true
    tty: true
    entrypoint: sh -c "/usr/local/bin/find-name.sh"
    profiles:
      - python
      - default
    
    depends_on:
      sidekick_service:
        condition: service_completed_successfully 
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/find-name.sh || exit 0"]
      interval: 5s
      timeout: 10s
      retries: 50
    volumes:
      - jenkins_home:/var/jenkins_home 
      - agent-ssh-dir:/ssh-dir 
      - ./secrets/:/secrets/ 
  jenkins_controller:
    image: ${IMAGE_PREFIX}/${GHCR_USERNAME}/quickstart-tutorials/jenkinsci-tutorials:simple_controller_${BRANCH_SUFFIX}
    restart: on-failure
    profiles:
      - python
      - default
    
    environment:
      - CASC_RELOAD_TOKEN=thisisnotsecure
    
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - agent-ssh-dir:/ssh-dir 
      - ./secrets/jcasc_token:/run/secrets/CASC_RELOAD_TOKEN:ro
    
    depends_on:
      sidekick_service:
        condition: service_completed_successfully 
    healthcheck:
      test: ["CMD-SHELL", "[ -f /ssh-dir/conductor_ok ] || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
  wizard_controller:
    image: jenkins/jenkins:2.452.1
    restart: on-failure
    profiles:
      - wizard
    ports:
      - "8080:8080"
    volumes:
      - empty_jenkins_home:/var/jenkins_home 
      - agent-ssh-dir:/ssh-dir 
    depends_on:
      sidekick_service:
        condition: service_completed_successfully 
    healthcheck:
      test: ["CMD-SHELL", "[ -f /ssh-dir/conductor_ok ] || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5

  default_agent:
    image: jenkins/ssh-agent:6.9.0
    container_name: desktop-jenkins_agent-1
    profiles:
      - default
    depends_on:
      sidekick_service:
        condition: service_completed_successfully 
      jenkins_controller:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "[ -f /home/jenkins/.ssh/authorized_keys ] || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - agent-ssh-dir:/home/jenkins/.ssh:ro 
  wizard_agent:
    image: jenkins/ssh-agent:5.37.0
    container_name: desktop-jenkins_agent-1
    profiles:
      - wizard
    depends_on:
      sidekick_service:
        condition: service_completed_successfully 
      wizard_controller:
        condition: service_started
    volumes:
      - agent-ssh-dir:/home/jenkins/.ssh:ro 
  
  python:
    image: ${IMAGE_PREFIX}/${GHCR_USERNAME}/quickstart-tutorials/jenkinsci-tutorials:python_agent_${BRANCH_SUFFIX}
    container_name: desktop-jenkins_agent-python
    profiles:
      - python
    depends_on:
      sidekick_service:
        condition: service_completed_successfully 
      jenkins_controller:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "[ -f /home/jenkins/.ssh/authorized_keys ] || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - agent-ssh-dir:/home/jenkins/.ssh:ro
  
volumes:
  jenkins_home: null
  empty_jenkins_home: null
  agent-ssh-dir:
    name: agent-ssh-dir 
