name: Run Tests
on: [push, pull_request]
jobs:
  Set-up-Django-Project:
    runs-on : ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version:
        - "3.12"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '2'

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version}}

    - name: Install pipx
      run: |
        sudo apt update
        sudo apt install pipx
        pipx ensurepath 

    - name: Install poetry
      run: |
        pipx install poetry

    - name: Run Tests
      run: |
        poetry install
        python manage.py migrate
        pytest --cov-branch --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
