name-template: $NEXT_MINOR_VERSION
tag-template: $NEXT_MINOR_VERSION
version-template: $MAJOR.$MINOR

categories:
  - title: "🐛 Bug fixes"
    labels:
      - bug
      - fix
      - bugfix
  - title: "🚀 New features and improvements"
    labels:
      - enhancement
      - feature
  - title: "📝 Documentation updates"
    labels:
      - documentation
  - title: "🚦 Tests"
    labels:
      - test
      - tests
  - title: "👻 Maintenance"
    labels:
      - chore
      - internal
      - maintenance

exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog

template: |
  $CHANGES

autolabeler:
  - label: "documentation"
    files:
      - "*.md"
  - label: "bug"
    branch:
      - "/fix\/.+/"
    title:
      - "/fix/i"
  - label: "enhancement"
    branch:
      - "/feature\/.+/"